### ISSUE TITLE
win10无法安装

### ISSUE THREAD

**Issue by zhangpenglink** [tsyeyuanfeng/bsdp#2]
```
C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\bsdp>if not defined npm_config_node_gyp (node "C:\Users\zhangpeng\AppData\Roaming\nvm\v8.9.1\node_modules\np
m\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  main.cc
  win_delay_load_hook.cc
  bsdiff.c
  bspatch.c
  bzlib.c
  compress.c
..\src\bspatch\bspatch.c(38): fatal error C1083: Cannot open include file: 'err.h': No such file or directory [C:\Users\zhangpeng\AppData\Roaming\npm\node_modu
les\bsdp\build\bsdiff.vcxproj]
..\src\bsdiff\bsdiff.c(35): fatal error C1083: Cannot open include file: 'err.h': No such file or directory [C:\Users\zhangpeng\AppData\Roaming\npm\node_module
s\bsdp\build\bsdiff.vcxproj]
  crctable.c
  randtable.c
..\src\bzip2\compress.c(205): warning C4244: '=': conversion from '__int64' to 'Int32', possible loss of data [C:\Users\zhangpeng\AppData\Roaming\npm\node_modu
les\bsdp\build\bsdiff.vcxproj]
  blocksort.c
  huffman.c
  decompress.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zhangpeng\AppData\Roaming\nvm\v8.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zhangpeng\\AppData\\Roaming\\nvm\\v8.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\bsdp
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bsdp@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bsdp@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhangpeng\AppData\Roaming\npm-cache\_logs\2018-01-16T06_56_25_830Z-debug.log

```
总是报这个，已经装了python2.7+gcc+node_gyp，还是不行

**Comment by Smackzter** [comment]
Was a fix for this found?

**Comment by Brouilles** [comment]
Same issue here :/

**Comment by Brouilles** [comment]
I have made an npm extension for bsdiff who works on Windows, Mac and Linux. Available here: https://github.com/Dezeiraud/bsdiff-nodejs
@Smackzter @zhangpenglink
